#!/usr/local/bin/node

var exec = require('child_process').exec,
    child;

child = exec('git remote -v',
  function (error, stdout, stderr) {
  	if (error !== null) {
  		console.error(error);
  		return;
  	}

  	var regex = /\:(\w+)\/(\w+)(?:\.git| )/;
  	var repo;
  	var githubUser;

	if (stdout.length > 0) {
		var strs = stdout.split('\n');

		for (var i = 0; i < strs.length; i++) {

			var str = strs[i];

			if (str.indexOf('github.yandex-team') === -1) {
				continue;
			}

			var matches = regex.exec(str);
			if (matches && matches.length === 3) {
				githubUser = matches[1];
				repo = matches[2];
				break;
			}
		}

		if (!repo) {
			console.error('No appropriate remotes found');
			return; 
		}

		var url = 'http://github.yandex-team.ru/' + githubUser + '/' + repo + '/commit/';

		var gitLog = exec('git log HEAD -1 --pretty="%H"', function(error, stdout, stderr) {
			if (error !== null) {
				console.error(error);
				return;
			}

			url = url + stdout;

			console.log(url);

		});


	}
  	
});