#!/bin/bash

current_dir=`pwd`

found=0

while read p; do
	if [[ $current_dir =~ .*$p/.* ]] || [[ $current_dir = $p ]];
	then
		found=$(($found+1))
		daria_repo=$p
	fi
done < ~/bin/daria_repos

if [[ $found -gt 1 ]]; then
	echo "Error: several daria repos found" 1>&2
	exit 2
fi

if [[ $found -eq 0 ]]; then
	echo "Error: couldn't find appropriate daria repo" 1>&2
	exit 1
fi

echo $daria_repo
