#!/bin/bash
tmp=$(daria_repo) && cd "$tmp/mail"

function _link {
	[ -d static ] && mv 'static/' 'static_'
    [ -d loc ] && mv 'loc/' 'loc_'
    [ -d jane ] && mv 'jane/' 'jane_'
    
    ln -s "../neo2/static" 'static'
    ln -s "../neo2/loc" 'loc'
    ln -s "../neo2" 'jane'
}

function _unlink {
	[ -d static_ ] && unlink 'static' && mv 'static_/' 'static'
    [ -d loc_ ] && unlink 'loc' && mv 'loc_/' 'loc'
    [ -d jane_ ] && unlink 'jane' && mv 'jane_/' 'jane'
}

if [ $1 ];
then
	if [ $1 = "t" ]; then
		_link

		exit
	fi
    
    if [ $1 = "f" ]; then
		_unlink

		exit
	fi

	echo "Error: bad arguments" 1>&2
	exit 1
else
    
    if [ -d jane ]; then
		if [ -L jane ] && [ -d jane_ ]; then
			_unlink
		else
			_link
		fi
	else
		echo "Error: there is no jane folder" 1>&2
		exit 1
	fi
fi

