#!/bin/bash

PROJECTS='boot jane mail'
#PROJECTS='boot jane mail disk promo'

tmp=$(daria_repo) && cd "$tmp"

if [ $1 ]; then
    if [ $1 == 'cl' ]; then
        make static clean
        exit 0
    elif [ $1 == 'all' ]; then
        make static PROJECTS="$PROJECTS"
        exit 0
    fi
fi

if [ $1 ]; then
    make static PROJECTS="$PROJECTS" THEMES="$1 $2 $3 $4 $5 $6 $7"
else
    make static PROJECTS="$PROJECTS" THEMES='colorful'
fi

