#!/bin/bash

tmp=$(daria_repo) && cd "$tmp/host-root2"

if [ $1 ]; then
    if [ $1 == 'cl' ]; then
        make clean
    elif [ $1 == 'all' ]; then
        make
    else
        make LANGS="ru $1 $2 $3 $4 $5 $6 $7"
    fi
else
    make LANGS='ru'
fi

