#!/bin/bash

liundo=0
stashed=0

li f 2>/dev/null
li_result=$?

git stash

#if [[ $1 == stash ]] || [[ $2 == stash ]]; then
#    git stash
#    [ $? ] && exit
#    stashed=1
#fi

if [ $1 ] && [[ $1 != stash ]]; then
    git checkout $1 \
    && git fetch -p \
    && git pull --rebase \
    && git submodule update \
    #&& [ -d jane ] && cd jane && git submodule update && cd -
else
    git fetch -p \
    && git pull --rebase \
    && git submodule update \
    #&& [ -d jane ] && cd jane && git submodule update && cd -
fi

if [ $stashed == 1 ]; then
    git stash pop
fi

